defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: *

development:
  <<: *defaults
  database: bqey_development

test:
  <<: *defaults
  database: bqey_test

production:
  <<: *defaults
  database: bqey_production
